import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import UserProvider from "@/context/UserProvider";
import { CookiesProvider } from "next-client-cookies/server";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tee Cheap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
          <CookiesProvider>
        {/* <UserProvider> */}
        <Navbar/>
      {children}
      <Toaster />
      <Footer/>
      {/* </UserProvider> */}
      </CookiesProvider>
      </body>
    </html>
  );
}
